---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: workshops-gitops
  namespace: package-installs
  annotations:
    educates_gitops_environment: "sample-environment"
    kapp.k14s.io/disable-original: ""
spec:
  serviceAccountName: workshops-gitops-package-installs
  syncPeriod: "0h2m0s"
  fetch:
    - inline:
        pathsFrom:
          - secretRef:
              name: versions
      path: environments
    - image:
        url: registry.default.svc.cluster.local/gitops-configurer:devel
        subPath: "gitops-app/src/bundle/config"
      path: config
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - config/ytt
          - config/kapp
        valuesFrom:
          - path: environments/versions.yaml
          - downwardAPI:
              items:
                - name: environment
                  fieldPath: metadata.annotations['educates_gitops_environment']
  deploy:
    - kapp:
        rawOptions: ["--app-changes-max-to-keep=5", "--wait-timeout=5m", "--diff-changes=true"]
