apiVersion: v1
kind: Secret
metadata:
  name: workshops
  namespace: package-installs
  annotations:
    kapp.k14s.io/disable-original: ""
stringData:
  workshops.yaml: |
    portals:
      - name: "workshop-bundle-animals"
        title: "Animals workshops"
        sessions:
          max: 2
        defaults:
          expires: 10m
          orphaned: 5m
          reserved: 0
        workshops:
          - name: workshop-dog
            expires: 60m
            orphaned: 5m
            reserved: 1
          - name: workshop-cat
          - name: workshop-bird
          - name: workshop-fish
          - name: workshop-giraffe
      - name: "workshop-bundle-colours"
        sessions:
          max: 2
        defaults:
          expires: 10m
          orphaned: 5m
          reserved: 24
        credentials:
          admin:
            username: user
            password: password
        workshops:
          - name: workshop-red
          - name: workshop-blue
          - name: workshop-green
