apiVersion: v1
kind: Secret
metadata:
  name: versions
  namespace: package-installs
  annotations:
    kapp.k14s.io/disable-original: ""
stringData:
  versions.yaml: |
    mode: "one_app"
    overlays:
      url: registry.default.svc.cluster.local/gitops-configurer
      version: devel
    config:
      type: "local"
      # local: 
      #   secretRef:
      #     common:
      #       name: common
      #       namespace: package-installs
      #     workshops:
      #       name: workshops
      #       namespace: package-installs
      subPath: "config"
    workshop_bundles:
      - name: "workshop-animals"
        url: "ghcr.io/educates/educates-workshop-gitops-configurer-workshop-bundle-animals-manifests"
        #semver: ">=1.0.0"
        version: "latest"
      - name: "workshop-colours"
        url: "ghcr.io/educates/educates-workshop-gitops-configurer-workshop-bundle-colours-manifests"
        version: "develop"
