apiVersion: v1
kind: Secret
metadata:
  name: common
  namespace: package-installs
  annotations:
    kapp.k14s.io/disable-original: ""
stringData:
  common.yaml: |
    live_updates: True
    theme_name: light-theme
    ancestors:
      - https://workshops-test.live
    sessions:
      anonymous: 1
      registered: 4
      max: 10
    index: https://workshops-test.live
    registration:
      enabled: false
      type: anonymous
    cookies_domain: workshops-test.live
    analytics:
      webhook_url: "https://metrics.educates.dev/?client=name&token=password"
