---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: workshops-gitops
  namespace: package-installs
spec:
  serviceAccountName: workshops-gitops-package-installs
  syncPeriod: "0h2m0s"
  fetch:
    - image:
        url: ghcr.io/educates/educates-workshop-gitops-configurer:main
        subPath: "gitops-app/src/bundle/config"
      path: config
    - git:
        url: https://github.com/educates/educates-workshop-gitops-configurer
        ref: origin/main
        subPath: "config/sample-environment"
      path: environment
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - config
        valuesFrom:
          - path: environment/versions.yaml
  deploy:
    - kapp:
        rawOptions: ["--app-changes-max-to-keep=5", "--wait-timeout=5m"]
