#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@ if data.values.config.type == "local":

#@ def config_secretcopier(name, ns_from, ns_to):
#@ if ns_from != ns_to:
kind: SecretCopier
apiVersion: secrets.educates.dev/v1beta1
metadata:
  annotations:
    kapp.k14s.io/change-group: local-config-secrets
  name: #@ "{}-{}".format(name, ns_to)
spec:
  rules:
    - reclaimPolicy: Delete
      sourceSecret:
        name: #@ name
        namespace: #@ ns_from
      targetNamespaces:
        nameSelector:
          matchNames:
            -  #@ ns_to
#@ end
#@ end #! config_secretcopier

#@ if data.values.mode == "app_per_bundle":

#@ for bundle in data.values.workshop_bundles:
--- #@ config_secretcopier(data.values.config.local.secretRef.common.name, data.values.config.local.secretRef.common.namespace, "workshops-{}".format(bundle.name))
--- #@ config_secretcopier(data.values.config.local.secretRef.workshops.name, data.values.config.local.secretRef.workshops.namespace, "workshops-{}".format(bundle.name))
#@ end

#@ else:

#@ for bundle in data.values.workshop_bundles:

--- #@ config_secretcopier(data.values.config.local.secretRef.common.name, data.values.config.local.secretRef.common.namespace, "workshops-{}".format("global"))
--- #@ config_secretcopier(data.values.config.local.secretRef.workshops.name, data.values.config.local.secretRef.workshops.namespace, "workshops-{}".format("global"))

#@ end #! for

#@ end #! if/else

#@ end #! data.values.config.type == "local"
